import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Archivo, Noto_Sans_JP, Open_Sans, Poppins } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/custom/SideBar";

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

const notoSans = Noto_Sans_JP({
  weight: ['400', '500', '700'],
  style: ['normal'],
  subsets: ['cyrillic'],
  display: 'swap' // <-- here
})
const open_sans = Open_Sans({
  weight: ['400', '500', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap' // <-- here
});
const archivo = Archivo({
  weight: ['400', '500', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap' // <-- here
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${archivo.className} md:grid md:grid-cols-[120px_1fr] bg-earth-100`}>
        <SideBar/>
        {children}</body>
    </html>
  );
}
